# Generated by Django 3.1 on 2020-10-13 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20201013_1912'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingclass',
            name='timestamp',
            field=models.DateTimeField(default=None),
        ),
    ]
