# Generated by Django 3.1 on 2020-10-13 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_bookingclass_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingclass',
            name='count',
            field=models.IntegerField(default=0),
        ),
    ]
