# Generated by Django 3.1 on 2020-10-17 04:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_bookingclass_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingclass',
            name='class_name',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='room',
            name='status',
            field=models.CharField(choices=[(0, 'off'), (1, 'on')], default=0, max_length=255),
        ),
        migrations.CreateModel(
            name='ClassRoom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_name', models.CharField(max_length=255)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('timestamp', models.DateTimeField(default=None)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.room')),
            ],
        ),
    ]
