# Generated by Django 3.1 on 2020-10-17 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20201017_1106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='status',
            field=models.CharField(choices=[(0, 'off'), (1, 'on')], default='off', max_length=255),
        ),
    ]
