# Generated by Django 3.1 on 2020-10-18 09:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20201017_1119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingclass',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms_booking', to='api.room'),
        ),
        migrations.AlterField(
            model_name='classroom',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms_class', to='api.room'),
        ),
    ]
