# Generated by Django 3.1 on 2020-10-26 03:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20201018_1634'),
    ]

    operations = [
        migrations.AlterField(
            model_name='floor',
            name='building',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='building_of_floor', to='api.building'),
        ),
    ]
